# Generated by Django 6.1 on 2026-08-12 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('leads_count', models.PositiveIntegerField(default=0, verbose_name='Лиды')),
                ('clients_count', models.PositiveIntegerField(default=0, verbose_name='Клиенты')),
                ('contracts_count', models.PositiveIntegerField(default=0, verbose_name='Контракты')),
                ('campaigns_count', models.PositiveIntegerField(default=0, verbose_name='Кампании')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Выручка')),
                ('avg_contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Средний чек контракта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновлено кем')),
            ],
            options={
                'verbose_name': 'Ежедневный отчёт',
                'verbose_name_plural': 'Ежедневные отчёты',
                'ordering': ['-date'],
            },
        ),
    ]
