# Generated by Django 6.1 on 2026-08-12 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, unique=True, verbose_name='Номер договора')),
                ('title', models.CharField(max_length=255, verbose_name='Название/предмет')),
                ('type', models.CharField(choices=[('supply', 'Поставка'), ('service', 'Оказание услуг'), ('license', 'Лицензия/подписка'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип договора')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан'), ('active', 'Активен'), ('completed', 'Завершен'), ('cancelled', 'Расторгнут')], default='draft', max_length=20, verbose_name='Статус')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договора')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
            },
        ),
    ]
