# Generated by Django 6.1 on 2026-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('private', 'Частное лицо'), ('company', 'Компания')], default='private', max_length=20, verbose_name='Тип клиента')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('potential', 'Потенциальный'), ('lost', 'Потерянный'), ('blocked', 'Заблокирован')], default='potential', max_length=20, verbose_name='Статус')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(blank=True, help_text='Для юрлиц', max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, help_text='Для юрлиц', max_length=20, verbose_name='КПП')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
